version: '2'
services:
  web:
    build: .
    ports:
     - "8080:5000"
    volumes:
     - .:/code
    networks:
      - redis-network
  redis:
    image: "redis:alpine"
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge  
